"""Tests for the script generator.

The generated file is a committed artifact a scientist reads and runs, so the
checks here are about it being *correct Python that means the right thing* --
not about its exact formatting.
"""

from __future__ import annotations

import ast
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import pytest

from nr_workbench.codegen.generator import generate, verify_self_hash
from nr_workbench.spec.models import ModelSpec
from nr_workbench.spec.resolve import Measurement, build_table

FIXED_TIME = datetime(2026, 8, 5, 12, 0, 0, tzinfo=UTC)

BASE: dict[str, Any] = {
    "schema": "nrw-model/1",
    "name": "demo",
    "materials": {"Air": {"rho": 0.0}, "Film": {"rho": 4.0}, "Si": {"rho": 2.07}},
    "stack": [
        {"name": "Air", "thickness": 0, "roughness": 5},
        {"name": "Film", "thickness": 100, "roughness": 5},
        {"name": "Si"},
    ],
    "states": [
        {
            "name": "a",
            "segments": [
                {"file": "d/a0.txt", "theta": 0.45},
                {"file": "d/a1.txt", "theta": 1.2},
            ],
        },
        {"name": "b", "segments": [{"file": "d/b0.txt", "theta": 0.45}]},
    ],
    "parameters": [
        {"path": "Film.thickness", "range": [50, 200], "per": "state"},
        {"path": "Film.rho", "range": [2, 6], "per": "model"},
    ],
}


def table_from(payload: dict[str, Any], counts: dict[str, int]):
    """Build a parameter table with fabricated measurements."""
    spec = ModelSpec.model_validate(payload)
    measurements = {
        group: [
            Measurement(group, i, f"d/{group}{i}.txt", 0.45, time=float(i * 100))
            for i in range(n)
        ]
        for group, n in counts.items()
    }
    return build_table(spec, measurements)


@pytest.fixture
def source() -> str:
    """A generated script for the base spec."""
    return generate(table_from(BASE, {"a": 2, "b": 1}), now=FIXED_TIME)


# --------------------------------------------------------------------------
# It has to be valid, readable Python
# --------------------------------------------------------------------------


def test_output_parses(source: str) -> None:
    ast.parse(source)


def test_output_is_ruff_clean(tmp_path: Path, source: str) -> None:
    """A generated file a human reads should not be visibly worse than one they write."""
    import shutil
    import subprocess
    import sys

    # Prefer the ruff in the active environment over whatever is on PATH.
    candidate = Path(sys.executable).parent / "ruff"
    ruff = str(candidate) if candidate.exists() else shutil.which("ruff")
    if ruff is None:
        pytest.skip("ruff is not available")

    script = tmp_path / "generated.py"
    script.write_text(source, encoding="utf-8")
    result = subprocess.run(
        [ruff, "check", "--select", "E9,F", "--no-cache", str(script)],
        capture_output=True,
        text=True,
        timeout=120,
    )

    assert result.returncode == 0, result.stdout


def test_header_records_provenance(source: str) -> None:
    assert "GENERATED BY nr-workbench" in source
    assert "DO NOT EDIT" in source
    assert "nrw model fork" in source


def test_self_hash_round_trips(source: str) -> None:
    """`nrw check` uses this to tell a hand-edited script from a stale one."""
    assert verify_self_hash(source)


def test_self_hash_detects_an_edit(source: str) -> None:
    tampered = source.replace("problem.name = 'demo'", "problem.name = 'edited'")

    assert tampered != source
    assert not verify_self_hash(tampered)


def test_generation_is_deterministic() -> None:
    """Same spec, same output -- otherwise every regeneration is a diff."""
    first = generate(table_from(BASE, {"a": 2, "b": 1}), now=FIXED_TIME)
    second = generate(table_from(BASE, {"a": 2, "b": 1}), now=FIXED_TIME)

    assert first == second


def test_no_absolute_paths(source: str) -> None:
    """An absolute path is what made the hand-written scripts unshareable."""
    offenders = [
        line
        for line in source.splitlines()
        if ('"/' in line or "'/" in line) and "PROJECT_ROOT" not in line
    ]

    assert offenders == []


def test_project_root_is_located_not_hardcoded(source: str) -> None:
    assert "nrw.toml" in source
    assert "def _project_root" in source


# --------------------------------------------------------------------------
# The three passes
# --------------------------------------------------------------------------


def test_each_free_parameter_is_created_exactly_once(source: str) -> None:
    """Pass 1's guarantee, and the reason the aliasing trap cannot happen."""
    creations = [
        line
        for line in source.splitlines()
        if line.startswith("P['") and "Parameter(" in line
    ]
    keys = [line.split("'")[1] for line in creations]

    assert len(keys) == len(set(keys))


def test_assignments_read_only_from_the_tables(source: str) -> None:
    """Pass 3 never reads from another Experiment; that is the whole design."""
    tree = ast.parse(source)
    for node in ast.walk(tree):
        if not isinstance(node, ast.Assign):
            continue
        target = ast.unparse(node.targets[0])
        if not target.startswith(("SAMPLES[", "EXP[")):
            continue
        if ".probe." not in target and "]." not in target:
            continue
        value = ast.unparse(node.value)
        assert value.startswith(("P[", "E[")), (
            f"assignment reads from something other than the table: {target} = {value}"
        )


def test_shared_parameters_produce_identity_assertions(source: str) -> None:
    """The pitfall becomes an executable check inside the artifact."""
    assert "def _check_links()" in source
    assert " is " in source
    assert "not shared as the spec requires" in source


def test_expected_free_count_is_asserted(source: str) -> None:
    table = table_from(BASE, {"a": 2, "b": 1})

    assert f"expected_free = {table.n_free}" in generate(table, now=FIXED_TIME)


# --------------------------------------------------------------------------
# Resolution modes and constraints
# --------------------------------------------------------------------------


def test_angular_only_emits_zero_wavelength_spread(source: str) -> None:
    assert "dL = 0 * q" in source
    assert "delta_wl_over_wl" not in source


def test_moderator_resolution_is_rejected_with_an_explanation() -> None:
    """The retired convention must fail loudly, not silently change the physics.

    It computed dL as `delta_wl_over_wl(wl) * q` -- by q rather than wl -- and
    results under it are not comparable with angular-only ones. A bare "input
    should be 'angular_only'" would not tell anyone that.
    """
    from nr_workbench.spec.models import SpecError

    payload = {**BASE, "probe": {"resolution": "moderator", "dq_is_fwhm": True}}

    with pytest.raises(
        (SpecError, Exception), match="no longer supported|angular_only"
    ):
        ModelSpec.model_validate(payload)


def test_sigma_input_is_converted_to_fwhm() -> None:
    payload = {**BASE, "probe": {"resolution": "angular_only", "dq_is_fwhm": False}}

    source = generate(table_from(payload, {"a": 2, "b": 1}), now=FIXED_TIME)

    assert "dq = dq * 2.355" in source


def test_pmath_is_imported_only_when_a_form_needs_it() -> None:
    payload = {
        **BASE,
        # Restricted to the two states: the series' value comes from the
        # constraint, and declaring it free there too would (rightly) be
        # rejected as a double assignment.
        "parameters": [
            {
                "path": "Film.thickness",
                "range": [50, 200],
                "per": "state",
                "in": ["a", "b"],
            },
        ],
        "series": [{"name": "t", "reduced_dir": "d"}],
        "constraints": [
            {
                "series": "t",
                "form": "logistic",
                "from": "a",
                "to": "b",
                "paths": ["Film.thickness"],
            }
        ],
    }

    with_logistic = generate(
        table_from(payload, {"a": 2, "b": 1, "t": 4}), now=FIXED_TIME
    )
    without = generate(table_from(BASE, {"a": 2, "b": 1}), now=FIXED_TIME)

    assert "from bumps.parameter import pmath" in with_logistic
    assert "pmath" not in without


def test_roughness_is_emitted_as_refl1d_interface(source: str) -> None:
    """The spec's friendly name has to become refl1d's actual attribute."""
    payload = {
        **BASE,
        "parameters": [
            {"path": "Film.roughness", "range": [1, 20], "per": "state"},
        ],
    }

    generated = generate(table_from(payload, {"a": 2, "b": 1}), now=FIXED_TIME)

    assert ".interface = P[" in generated
    assert ".roughness = P[" not in generated


def test_post_build_is_emitted_verbatim_and_flagged() -> None:
    payload = {**BASE, "post_build": "problem.name = 'overridden'\n"}

    source = generate(table_from(payload, {"a": 2, "b": 1}), now=FIXED_TIME)

    assert "problem.name = 'overridden'" in source
    assert "escape hatch" in source.lower()


# --------------------------------------------------------------------------
# probe.dq_scale
#
# A correction for a reduction whose resolution estimate is wrong. Fixed rather
# than fitted because refl1d has nothing to bind a fitted scale to: `Probe.dQ`
# is a property over a fixed array plus `sample_broadening`, and
# `Probe.parameters()` exposes five knobs, none of them a dQ scale.
# --------------------------------------------------------------------------


def test_dq_scale_reaches_the_generated_probe() -> None:
    payload = {
        **BASE,
        "probe": {"resolution": "angular_only", "dq_is_fwhm": True, "dq_scale": 4.1},
    }

    source = generate(table_from(payload, {"a": 2, "b": 1}), now=FIXED_TIME)

    assert "dq = dq * 4.1" in source
    assert "probe.dq_scale" in source, "and says where the number came from"


def test_the_default_scale_emits_no_multiplication() -> None:
    """A no-op line in every generated script is noise that invites editing."""
    payload = {**BASE, "probe": {"resolution": "angular_only"}}
    source = generate(table_from(payload, {"a": 2, "b": 1}), now=FIXED_TIME)

    assert "dq = dq * 1.0" not in source
    assert "dq_scale" not in source


def test_a_scale_composes_with_a_sigma_column() -> None:
    """Both corrections are about the same column and both must apply."""
    payload = {
        **BASE,
        "probe": {"resolution": "angular_only", "dq_is_fwhm": False, "dq_scale": 2.0},
    }

    source = generate(table_from(payload, {"a": 2, "b": 1}), now=FIXED_TIME)

    assert "dq = dq * 2.355" in source
    assert "dq = dq * 2.0" in source
    assert source.index("2.355") < source.index("dq = dq * 2.0"), (
        "convert to FWHM first, then correct the magnitude"
    )


# --------------------------------------------------------------------------
# trim: cutting data that no parameter can absorb
#
# A segment whose required scale varies *across* its own wavelength band cannot
# be fixed by probe.intensity, which is one number per segment. Left in, the fit
# spends a thickness or a roughness on it. Cutting it was previously only
# possible via `nrw model fork`, which takes the model out of the spec for the
# sake of two numbers.
# --------------------------------------------------------------------------

TRIM_REASON = "required scale varies across the band; no intensity can absorb it"


def test_a_trim_reaches_only_the_measurement_it_names() -> None:
    payload = {
        **BASE,
        "trim": [{"in": ["a#0"], "lambda_min": 3.5, "reason": TRIM_REASON}],
    }

    source = generate(table_from(payload, {"a": 2, "b": 1}), now=FIXED_TIME)

    calls = [
        line
        for line in source.splitlines()
        if "create_probe(" in line and "def " not in line
    ]
    assert "lambda_min=3.5" in calls[0]
    assert all("lambda_min" not in line for line in calls[1:])


def test_a_global_trim_reaches_every_measurement() -> None:
    payload = {**BASE, "trim": [{"q_max": 0.2, "reason": TRIM_REASON}]}

    source = generate(table_from(payload, {"a": 2, "b": 1}), now=FIXED_TIME)

    calls = [
        line
        for line in source.splitlines()
        if "create_probe(" in line and "def " not in line
    ]
    assert calls and all("q_max=0.2" in line for line in calls)


def test_a_later_entry_narrows_an_earlier_one_field_by_field() -> None:
    """So a blanket cut can be tightened for one segment without restating it."""
    payload = {
        **BASE,
        "trim": [
            {"lambda_min": 2.5, "reason": TRIM_REASON},
            {"in": ["a#0"], "lambda_min": 3.5, "reason": "worse on this one"},
        ],
    }

    source = generate(table_from(payload, {"a": 2, "b": 1}), now=FIXED_TIME)

    calls = [
        line
        for line in source.splitlines()
        if "create_probe(" in line and "def " not in line
    ]
    assert "lambda_min=3.5" in calls[0]
    assert "lambda_min=2.5" in calls[1]


def test_a_spec_with_no_trim_generates_what_it_did_before() -> None:
    """No dead parameters, and regenerating an untouched spec makes no diff."""
    source = generate(table_from(BASE, {"a": 2, "b": 1}), now=FIXED_TIME)

    assert "def create_probe(data_file, theta):" in source
    assert "lambda_min" not in source
    assert "the trim bounds keep no points" not in source


def test_the_generated_probe_refuses_a_trim_that_keeps_nothing() -> None:
    """Better to fail there than hand refl1d an empty probe."""
    payload = {**BASE, "trim": [{"q_min": 99.0, "reason": TRIM_REASON}]}

    source = generate(table_from(payload, {"a": 2, "b": 1}), now=FIXED_TIME)

    assert "the trim bounds keep no points" in source
    assert "raise ValueError" in source


def test_a_layer_name_is_emitted_as_a_literal_not_interpolated() -> None:
    """Layer names now reach the generator from a language model, via
    `nrw aure import`.

    `_NAME_RE` is the only thing keeping quotes and backslashes out, and `$`
    used to let a trailing newline through -- which emitted an unterminated
    string literal and a SyntaxError three commands later, blamed on a name
    the scientist never typed. `repr` is correct whatever the regex allows.
    """
    from nr_workbench.spec.models import _NAME_RE

    assert not _NAME_RE.match("Cu\n"), "a trailing newline must not pass validation"


def test_a_layer_name_is_written_as_a_python_literal() -> None:
    """Not interpolated into a quoted string.

    Interpolation was safe only for as long as `_NAME_RE` stayed strict, and
    it already had one hole. `repr` is correct whatever the regex allows, and
    the generated file has to parse before anything else about it matters.
    """
    source = generate(table_from(BASE, {"a": 2, "b": 1}), now=FIXED_TIME)

    assert "SLD('" in source or 'SLD("' in source
    ast.parse(source)
