"""Tests for the script generator.

The generated file is a committed artifact a scientist reads and runs, so the
checks here are about it being *correct Python that means the right thing* --
not about its exact formatting.
"""

from __future__ import annotations

import ast
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import pytest

from nr_workbench.codegen.generator import generate, verify_self_hash
from nr_workbench.spec.models import ModelSpec
from nr_workbench.spec.resolve import Measurement, build_table

FIXED_TIME = datetime(2026, 8, 5, 12, 0, 0, tzinfo=UTC)

BASE: dict[str, Any] = {
    "schema": "nrw-model/1",
    "name": "demo",
    "materials": {"Air": {"rho": 0.0}, "Film": {"rho": 4.0}, "Si": {"rho": 2.07}},
    "stack": [
        {"name": "Air", "thickness": 0, "roughness": 5},
        {"name": "Film", "thickness": 100, "roughness": 5},
        {"name": "Si"},
    ],
    "states": [
        {
            "name": "a",
            "segments": [
                {"file": "d/a0.txt", "theta": 0.45},
                {"file": "d/a1.txt", "theta": 1.2},
            ],
        },
        {"name": "b", "segments": [{"file": "d/b0.txt", "theta": 0.45}]},
    ],
    "parameters": [
        {"path": "Film.thickness", "range": [50, 200], "per": "state"},
        {"path": "Film.rho", "range": [2, 6], "per": "model"},
    ],
}


def table_from(payload: dict[str, Any], counts: dict[str, int]):
    """Build a parameter table with fabricated measurements."""
    spec = ModelSpec.model_validate(payload)
    measurements = {
        group: [
            Measurement(group, i, f"d/{group}{i}.txt", 0.45, time=float(i * 100))
            for i in range(n)
        ]
        for group, n in counts.items()
    }
    return build_table(spec, measurements)


@pytest.fixture
def source() -> str:
    """A generated script for the base spec."""
    return generate(table_from(BASE, {"a": 2, "b": 1}), now=FIXED_TIME)


# --------------------------------------------------------------------------
# It has to be valid, readable Python
# --------------------------------------------------------------------------


def test_output_parses(source: str) -> None:
    ast.parse(source)


def test_output_is_ruff_clean(tmp_path: Path, source: str) -> None:
    """A generated file a human reads should not be visibly worse than one they write."""
    import shutil
    import subprocess
    import sys

    # Prefer the ruff in the active environment over whatever is on PATH.
    candidate = Path(sys.executable).parent / "ruff"
    ruff = str(candidate) if candidate.exists() else shutil.which("ruff")
    if ruff is None:
        pytest.skip("ruff is not available")

    script = tmp_path / "generated.py"
    script.write_text(source, encoding="utf-8")
    result = subprocess.run(
        [ruff, "check", "--select", "E9,F", "--no-cache", str(script)],
        capture_output=True,
        text=True,
        timeout=120,
    )

    assert result.returncode == 0, result.stdout


def test_header_records_provenance(source: str) -> None:
    assert "GENERATED BY nr-workbench" in source
    assert "DO NOT EDIT" in source
    assert "nrw model fork" in source


def test_self_hash_round_trips(source: str) -> None:
    """`nrw check` uses this to tell a hand-edited script from a stale one."""
    assert verify_self_hash(source)


def test_self_hash_detects_an_edit(source: str) -> None:
    tampered = source.replace("problem.name = 'demo'", "problem.name = 'edited'")

    assert tampered != source
    assert not verify_self_hash(tampered)


def test_generation_is_deterministic() -> None:
    """Same spec, same output -- otherwise every regeneration is a diff."""
    first = generate(table_from(BASE, {"a": 2, "b": 1}), now=FIXED_TIME)
    second = generate(table_from(BASE, {"a": 2, "b": 1}), now=FIXED_TIME)

    assert first == second


def test_no_absolute_paths(source: str) -> None:
    """An absolute path is what made the hand-written scripts unshareable."""
    offenders = [
        line
        for line in source.splitlines()
        if ('"/' in line or "'/" in line) and "PROJECT_ROOT" not in line
    ]

    assert offenders == []


def test_project_root_is_located_not_hardcoded(source: str) -> None:
    assert "nrw.toml" in source
    assert "def _project_root" in source


# --------------------------------------------------------------------------
# The three passes
# --------------------------------------------------------------------------


def test_each_free_parameter_is_created_exactly_once(source: str) -> None:
    """Pass 1's guarantee, and the reason the aliasing trap cannot happen."""
    creations = [
        line
        for line in source.splitlines()
        if line.startswith("P['") and "Parameter(" in line
    ]
    keys = [line.split("'")[1] for line in creations]

    assert len(keys) == len(set(keys))


def test_assignments_read_only_from_the_tables(source: str) -> None:
    """Pass 3 never reads from another Experiment; that is the whole design."""
    tree = ast.parse(source)
    for node in ast.walk(tree):
        if not isinstance(node, ast.Assign):
            continue
        target = ast.unparse(node.targets[0])
        if not target.startswith(("SAMPLES[", "EXP[")):
            continue
        if ".probe." not in target and "]." not in target:
            continue
        value = ast.unparse(node.value)
        assert value.startswith(("P[", "E[")), (
            f"assignment reads from something other than the table: {target} = {value}"
        )


def test_shared_parameters_produce_identity_assertions(source: str) -> None:
    """The pitfall becomes an executable check inside the artifact."""
    assert "def _check_links()" in source
    assert " is " in source
    assert "not shared as the spec requires" in source


def test_expected_free_count_is_asserted(source: str) -> None:
    table = table_from(BASE, {"a": 2, "b": 1})

    assert f"expected_free = {table.n_free}" in generate(table, now=FIXED_TIME)


# --------------------------------------------------------------------------
# Resolution modes and constraints
# --------------------------------------------------------------------------


def test_angular_only_emits_zero_wavelength_spread(source: str) -> None:
    assert "dL = 0 * q" in source
    assert "delta_wl_over_wl" not in source


def test_moderator_mode_emits_the_emission_time_polynomial() -> None:
    """Reproducing the REF_L convention exactly is what passed the gate."""
    payload = {**BASE, "probe": {"resolution": "moderator", "dq_is_fwhm": True}}

    source = generate(table_from(payload, {"a": 2, "b": 1}), now=FIXED_TIME)

    assert "def delta_wl_over_wl(wl):" in source
    assert "dL = delta_wl_over_wl(wl) * q" in source
    # The `* q` looks like a units slip; the comment must explain why it stays.
    assert "REF_L convention" in source


def test_sigma_input_is_converted_to_fwhm() -> None:
    payload = {**BASE, "probe": {"resolution": "angular_only", "dq_is_fwhm": False}}

    source = generate(table_from(payload, {"a": 2, "b": 1}), now=FIXED_TIME)

    assert "dq = dq * 2.355" in source


def test_pmath_is_imported_only_when_a_form_needs_it() -> None:
    payload = {
        **BASE,
        # Restricted to the two states: the series' value comes from the
        # constraint, and declaring it free there too would (rightly) be
        # rejected as a double assignment.
        "parameters": [
            {
                "path": "Film.thickness",
                "range": [50, 200],
                "per": "state",
                "in": ["a", "b"],
            },
        ],
        "series": [{"name": "t", "reduced_dir": "d"}],
        "constraints": [
            {
                "series": "t",
                "form": "logistic",
                "from": "a",
                "to": "b",
                "paths": ["Film.thickness"],
            }
        ],
    }

    with_logistic = generate(
        table_from(payload, {"a": 2, "b": 1, "t": 4}), now=FIXED_TIME
    )
    without = generate(table_from(BASE, {"a": 2, "b": 1}), now=FIXED_TIME)

    assert "from bumps.parameter import pmath" in with_logistic
    assert "pmath" not in without


def test_roughness_is_emitted_as_refl1d_interface(source: str) -> None:
    """The spec's friendly name has to become refl1d's actual attribute."""
    payload = {
        **BASE,
        "parameters": [
            {"path": "Film.roughness", "range": [1, 20], "per": "state"},
        ],
    }

    generated = generate(table_from(payload, {"a": 2, "b": 1}), now=FIXED_TIME)

    assert ".interface = P[" in generated
    assert ".roughness = P[" not in generated


def test_post_build_is_emitted_verbatim_and_flagged() -> None:
    payload = {**BASE, "post_build": "problem.name = 'overridden'\n"}

    source = generate(table_from(payload, {"a": 2, "b": 1}), now=FIXED_TIME)

    assert "problem.name = 'overridden'" in source
    assert "escape hatch" in source.lower()
