"""Emit a standalone refl1d script from a resolved parameter table.

The output is a real Python file a scientist can read, run with plain
``refl1d``/``bumps``, commit, and hand to a colleague who has never heard of
nr-workbench. It is shaped to look like the hand-written scripts it replaces so
it is recognisable, with three differences that matter:

* paths resolve from ``__file__``, never an absolute location;
* every parameter is created once in an explicit table, so the aliasing trap
  cannot occur (see :mod:`nr_workbench.spec.resolve`);
* it ends with ``_check_links()``, which asserts the sharing the spec asked for
  actually holds -- the pitfall as an executable check rather than a comment.

The LLM never writes this code. It writes the spec; this writes the Python.
That is deliberate: a generated script can be verified, and arbitrary emitted
code cannot.
"""

from __future__ import annotations

import hashlib
from datetime import UTC, datetime
from pathlib import Path

from nr_workbench.spec.resolve import ParameterTable

#: Written into the header so `nrw check` can tell a hand-edited script from a
#: stale one.
SELF_HASH_MARKER = "nrw:self"
SPEC_HASH_MARKER = "nrw:spec"

#: Fallback depth from a generated script to the project root when no nrw.toml
#: is found: samples/<id>/models/<name>.py -> parents[3].
_PROJECT_ROOT_DEPTH = 3


def generate(
    table: ParameterTable,
    *,
    spec_path: Path | None = None,
    spec_sha256: str = "",
    versions: dict[str, str] | None = None,
    now: datetime | None = None,
) -> str:
    """Render the script.

    Args:
        table: The resolved parameter table.
        spec_path: Path to the spec, relative to the project root.
        spec_sha256: Digest of the spec, recorded in the header.
        versions: Package versions to record.
        now: Generation timestamp. Injectable so golden tests are stable.

    Returns:
        The complete script source, with its self-hash filled in.
    """
    spec = table.spec
    stamp = (now or datetime.now(UTC)).strftime("%Y-%m-%dT%H:%M:%SZ")

    blocks = [
        _header(
            spec.name, spec_path, spec_sha256, stamp, versions or {}, spec.description
        ),
        _imports(table),
        _instrument_helpers(table),
        _stack(table),
        _experiments(table),
        _pass_one_free(table),
        _pass_two_expressions(table),
        _pass_three_assign(table),
        _problem(table),
        _check_links(table),
        _post_build(table),
        _main_guard(),
    ]
    source = "\n\n".join(b for b in blocks if b).rstrip("\n") + "\n"
    return _stamp_self_hash(source)


# --------------------------------------------------------------------------
# Header and preamble
# --------------------------------------------------------------------------


def _header(
    name: str,
    spec_path: Path | None,
    spec_sha256: str,
    stamp: str,
    versions: dict[str, str],
    description: str,
) -> str:
    """The do-not-edit banner, carrying everything needed to trace the file."""
    lines = [
        "# " + "-" * 74,
        "# GENERATED BY nr-workbench -- DO NOT EDIT",
        f"#   model:       {name}",
    ]
    if spec_path is not None:
        lines.append(f"#   spec:        {spec_path.as_posix()}")
    if spec_sha256:
        lines.append(f"#   spec sha256: {spec_sha256}  ({SPEC_HASH_MARKER})")
    lines.append(f"#   self sha256: {'0' * 64}  ({SELF_HASH_MARKER})")
    lines.append(f"#   generated:   {stamp}")
    if versions:
        lines.append(
            "#   " + " / ".join(f"{k} {v}" for k, v in sorted(versions.items()))
        )
    lines += [
        "#",
        "# To change this model, edit the spec and run `nrw model generate`.",
        "# To take manual ownership, run `nrw model fork` -- that keeps provenance.",
        "# " + "-" * 74,
    ]
    if description.strip():
        lines.append('"""')
        lines += [line.rstrip() for line in description.strip().splitlines()]
        lines.append('"""')
    return "\n".join(lines)


def _imports(table: ParameterTable) -> str:
    """Imports, including pmath only when a form actually needs it."""
    needs_pmath = any("pmath." in e.source for e in table.expressions)
    lines = [
        "from pathlib import Path",
        "",
        "import numpy as np",
        "from bumps.parameter import Parameter",
        "from refl1d.names import SLD, Experiment, FitProblem",
        "from refl1d.probe import make_probe",
    ]
    if needs_pmath:
        lines.append("from bumps.parameter import pmath")
    lines += [
        "",
        "",
        "def _project_root():",
        '    """Find the project root by walking up to nrw.toml.',
        "",
        "    Located rather than hardcoded so the script still works if it is moved,",
        "    and never an absolute path -- an absolute path is what made the",
        "    hand-written scripts unusable on anyone else's machine.",
        '    """',
        "    here = Path(__file__).resolve()",
        "    for candidate in here.parents:",
        '        if (candidate / "nrw.toml").is_file():',
        "            return candidate",
        f"    return here.parents[{_PROJECT_ROOT_DEPTH}]  # samples/<id>/models/<name>.py",
        "",
        "",
        "PROJECT_ROOT = _project_root()",
    ]
    return "\n".join(lines)


#: The SNS moderator emission-time polynomial, lifted verbatim from the
#: hand-written REF_L scripts. Two pieces, switching at 2 A.
_MODERATOR_HELPER = '''
def delta_wl_over_wl(wl):
    """Relative wavelength spread from the SNS moderator emission time.

    The emission-time polynomial gives a time in microseconds; the constants
    are the BL-4B flight geometry. Lifted verbatim from the hand-written REF_L
    scripts so results stay comparable with work done before this tool.
    """
    dtof = 0.0148 * wl * wl * wl - 0.5233 * wl * wl + 6.4797 * wl + 231.99
    dtof[wl > 2] = (
        392.31 * wl**6
        - 3169.3 * wl**5
        + 10445 * wl**4
        - 17872 * wl * wl * wl
        + 16509 * wl * wl
        - 7448.4 * wl
        + 1280.5
    )
    return 3.9560 * dtof / (1000000 * 15.282 * wl)
'''


def _instrument_helpers(table: ParameterTable) -> str:
    """The BL-4B probe construction, inlined so the script stands alone."""
    probe = table.spec.probe
    fwhm = probe.dq_is_fwhm
    moderator = probe.resolution == "moderator"

    lines = ["# --- instrument (BL-4B) " + "-" * 52]
    if moderator:
        lines.append(_MODERATOR_HELPER.rstrip("\n"))

    lines += [
        "",
        "",
        "def create_probe(data_file, theta):",
        '    """Angle-based probe from a 4-column Q, R, dR, dQ file.',
        "",
        "    dT comes from dQ at the known incident angle. dL is "
        + ("the moderator spread." if moderator else "zero: the angular-only"),
    ]
    if not moderator:
        lines.append("    convention REF_L reduction produces.")
    lines += [
        "",
        f"    The 4th column is {'FWHM' if fwhm else 'sigma'}, matching the file convention;",
        "    make_probe expects FWHM for both dT and dL.",
        '    """',
        "    q, data, errors, dq = np.loadtxt(data_file).T",
    ]
    if not fwhm:
        lines.append("    dq = dq * 2.355  # file holds sigma; make_probe wants FWHM")
    lines += [
        "    wl = 4 * np.pi * np.sin(np.pi / 180 * theta) / q",
        "    dT = dq / q * np.tan(np.pi / 180 * theta) * 180 / np.pi",
    ]
    if moderator:
        lines += [
            "    # Multiplied by q, not wl. That looks like a units slip, but it is the",
            "    # long-standing REF_L convention and every published fit from this",
            "    # beamline uses it -- changing it here would silently make new results",
            "    # incomparable with old ones.",
            "    dL = delta_wl_over_wl(wl) * q",
        ]
    else:
        lines.append("    dL = 0 * q")
    lines += [
        "    return make_probe(",
        "        T=theta, dT=dT, L=wl, dL=dL,",
        "        data=(data, errors),",
        '        radiation="neutron", resolution="uniform",',
        "    )",
    ]
    return "\n".join(lines)


def _stack(table: ParameterTable) -> str:
    """The sample factory: one stack definition, instantiated per measurement."""
    spec = table.spec
    lines = [
        "# --- stack " + "-" * 64,
        "",
        "",
        "def create_sample():",
        '    """Build the layer stack, ambient first."""',
    ]

    for name in spec.layer_names:
        layer = spec.layer(name)
        material = spec.materials.get(layer.material_key)
        if material is None:
            raise ValueError(
                f"layer {name!r} refers to material {layer.material_key!r}, "
                f"which is not defined under `materials`"
            )
        irho = f", irho={material.irho!r}" if material.irho else ""
        lines.append(f'    {_ident(name)} = SLD("{name}", rho={material.rho!r}{irho})')

    lines.append("")
    parts = []
    for i, name in enumerate(spec.layer_names):
        layer = spec.layer(name)
        if i == len(spec.layer_names) - 1:
            parts.append(_ident(name))  # substrate is semi-infinite
        else:
            parts.append(f"{_ident(name)}({layer.thickness!r}, {layer.roughness!r})")
    lines.append("    return " + " | ".join(parts))

    if spec.probe.back_reflection:
        lines.append("")
        lines.append("    # back_reflection: neutrons enter through the substrate")
    return "\n".join(lines)


def _experiments(table: ParameterTable) -> str:
    """Create every Experiment, grouped, before any parameter is touched."""
    lines = [
        "# --- experiments " + "-" * 58,
        "",
        "EXP = {}   # group -> [Experiment, ...]",
        "SAMPLES = {}   # group -> [sample, ...], for the identity checks below",
    ]
    for group, measurements in table.measurements.items():
        lines += ["", f"EXP[{group!r}] = []", f"SAMPLES[{group!r}] = []"]
        for m in measurements:
            comment = f"  # t = {m.time:g} s" if m.time is not None else ""
            lines += [
                f"_probe = create_probe(PROJECT_ROOT / {m.file!r}, {m.theta!r}){comment}",
                "_sample = create_sample()",
                f"EXP[{group!r}].append(Experiment(sample=_sample, probe=_probe))",
                f"SAMPLES[{group!r}].append(_sample)",
            ]
    return "\n".join(lines)


# --------------------------------------------------------------------------
# The three passes
# --------------------------------------------------------------------------


def _pass_one_free(table: ParameterTable) -> str:
    """PASS 1: create every free parameter exactly once."""
    lines = [
        "# --- PASS 1: create every free parameter, once " + "-" * 28,
        "#",
        "# Built from the spec, never by reading an Experiment. That is what makes",
        "# the aliasing trap impossible: there is no 'first segment' whose",
        "# parameter later reassignments could fail to propagate from.",
        "",
        "P = {}",
    ]
    for parameter in table.free:
        comment = f"  # {parameter.comment}" if parameter.comment else ""
        lines.append(
            f"P[{parameter.key!r}] = Parameter("
            f"value={parameter.value!r}, name={parameter.display!r}){comment}"
        )
        if parameter.bounds is not None:
            low, high = parameter.bounds
            lines.append(f"P[{parameter.key!r}].range({low!r}, {high!r})")
    if not table.free:
        lines.append("# (the spec declares no free parameters)")
    return "\n".join(lines)


def _pass_two_expressions(table: ParameterTable) -> str:
    """PASS 2: build constrained values from the free parameters only."""
    if not table.expressions:
        return ""
    lines = [
        "# --- PASS 2: constrained expressions " + "-" * 38,
        "#",
        "# Each is a bumps Parameter expression over the free parameters above, so",
        "# only the endpoints are fitted and the per-slice values follow.",
        "",
        "E = {}",
    ]
    last_comment = None
    for expression in table.expressions:
        if expression.comment != last_comment:
            lines.append(f"# {expression.comment}")
            last_comment = expression.comment
        lines.append(f"E[{expression.key!r}] = {expression.source}")
    return "\n".join(lines)


def _pass_three_assign(table: ParameterTable) -> str:
    """PASS 3: assign every slot from the table."""
    lines = [
        "# --- PASS 3: assign " + "-" * 55,
        "#",
        "# Every slot reads from P or E. No assignment reads from another",
        "# Experiment, so cross-state constraints cannot silently fail to",
        "# propagate to the other angle segments.",
    ]
    for group, measurements in table.measurements.items():
        for m in measurements:
            slots = table.slots_for(m)
            if not slots:
                continue
            lines.append("")
            lines.append(f"# {group}[{m.index}]  {Path(m.file).name}")
            for slot in slots:
                target = _assignment_target(group, m.index, slot)
                source = f"{slot.kind}[{slot.ref!r}]"
                lines.append(f"{target} = {source}")
    return "\n".join(lines)


def _assignment_target(group: str, index: int, slot) -> str:
    """The left-hand side for one slot."""
    if slot.path.is_probe:
        return f"EXP[{group!r}][{index}].probe.{slot.path.attr}"

    owner = f"SAMPLES[{group!r}][{index}][{slot.path.owner!r}]"
    attribute = {
        "thickness": "thickness",
        # refl1d calls it `interface`; `roughness` is the friendlier spelling
        # the spec uses.
        "roughness": "interface",
        "rho": "material.rho",
        "irho": "material.irho",
    }[slot.path.attr]
    return f"{owner}.{attribute}"


def _problem(table: ParameterTable) -> str:
    """Assemble the FitProblem in declaration order."""
    groups = " + ".join(f"EXP[{g!r}]" for g in table.measurements)
    return "\n".join(
        [
            "# --- problem " + "-" * 62,
            "",
            f"problem = FitProblem({groups})",
            f"problem.name = {table.spec.name!r}",
        ]
    )


def _check_links(table: ParameterTable) -> str:
    """Emit runtime assertions that the requested sharing actually holds.

    The aliasing pitfall as an executable test, inside the artifact itself, so
    it is checked wherever the script runs rather than only in our test suite.
    """
    shared: list[tuple[str, list[tuple[str, int, str]]]] = []
    by_ref: dict[str, list] = {}
    for slot in table.slots:
        if slot.kind == "P":
            by_ref.setdefault(slot.ref, []).append(slot)

    for ref, slots in by_ref.items():
        if len(slots) > 1:
            shared.append(
                (
                    ref,
                    [
                        (
                            s.measurement.group,
                            s.measurement.index,
                            _assignment_target(
                                s.measurement.group, s.measurement.index, s
                            ),
                        )
                        for s in slots
                    ],
                )
            )

    lines = [
        "# --- self-check " + "-" * 59,
        "",
        "",
        "def _check_links():",
        '    """Assert the parameter sharing the spec asked for actually holds.',
        "",
        "    Cheap insurance against the classic co-refinement bug, where angle",
        "    segments alias one parameter object and a later reassignment reaches",
        "    only one of them.",
        '    """',
        f"    expected_free = {table.n_free}",
        "    actual_free = len(problem.getp())",
        "    assert actual_free == expected_free, (",
        '        f"expected {expected_free} free parameters, found {actual_free}"',
        "    )",
    ]

    if shared:
        lines.append("")
        for ref, targets in sorted(shared)[:40]:
            first = targets[0][2]
            for _, _, target in targets[1:]:
                lines.append(
                    f"    assert {target} is {first}, "
                    f'"{ref} is not shared as the spec requires"'
                )

    lines += [
        "",
        "",
        'if __name__ == "__main__":',
        "    _check_links()",
        '    print(f"free parameters: {len(problem.getp())}")',
        '    print(f"chisq:           {problem.chisq():.6g}")',
    ]
    return "\n".join(lines)


def _post_build(table: ParameterTable) -> str:
    """Verbatim user Python, if the spec supplies any."""
    if not table.spec.post_build:
        return ""
    return "\n".join(
        [
            "# --- post_build (verbatim from the spec) " + "-" * 34,
            "#",
            "# An escape hatch. `nrw check` flags every use: each one is a report that",
            "# the schema cannot yet express something real.",
            "",
            table.spec.post_build.rstrip("\n"),
        ]
    )


def _main_guard() -> str:
    """The main guard is emitted with the self-check."""
    return ""


# --------------------------------------------------------------------------
# Helpers
# --------------------------------------------------------------------------


def _ident(name: str) -> str:
    """Turn a layer name into a valid Python identifier."""
    cleaned = "".join(c if c.isalnum() or c == "_" else "_" for c in name)
    return cleaned if not cleaned[0].isdigit() else f"_{cleaned}"


def _stamp_self_hash(source: str) -> str:
    """Replace the placeholder self-hash with the real digest.

    Hashed with the placeholder in place, so the value is reproducible: the
    digest covers the file as it would be *before* stamping, and `nrw check`
    recomputes it the same way.
    """
    digest = hashlib.sha256(source.encode("utf-8")).hexdigest()
    return source.replace(
        f"{'0' * 64}  ({SELF_HASH_MARKER})", f"{digest}  ({SELF_HASH_MARKER})", 1
    )


def verify_self_hash(source: str) -> bool:
    """Check a generated script has not been hand-edited.

    Args:
        source: The script's contents.

    Returns:
        True if the recorded digest matches the content.
    """
    import re

    match = re.search(
        rf"self sha256: ([0-9a-f]{{64}})  \({re.escape(SELF_HASH_MARKER)}\)", source
    )
    if match is None:
        return False
    recorded = match.group(1)
    restored = source.replace(
        f"{recorded}  ({SELF_HASH_MARKER})", f"{'0' * 64}  ({SELF_HASH_MARKER})", 1
    )
    return hashlib.sha256(restored.encode("utf-8")).hexdigest() == recorded
