"""Explaining a model in English, derived from the model itself.

A spec says what the model *is*. It does not say what was assumed, what is
being held equal to what, or why the fit has the number of free parameters it
has. Six months later, or to a reviewer, those are the questions -- and the
answers are usually in nobody's head any more.

So this writes them down. **Derived, never authored:** every sentence comes
from the resolved :class:`~nr_workbench.spec.resolve.ParameterTable`, so it
cannot describe a model other than the one that will actually be fitted. A
hand-written explanation drifts from the spec the first time someone edits one
and not the other; a generated one is either current or flagged stale by
``nrw check``.

It is regenerated alongside the script by ``nrw model generate``, and carries
the spec's hash so staleness is detectable.
"""

from __future__ import annotations

from collections import defaultdict
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from nr_workbench.spec.resolve import ParameterTable

#: Marker carrying the spec digest, so `nrw check` can spot a stale document.
SPEC_HASH_MARKER = "nrw:spec"

#: Section headings for each scope.
_SCOPE_HEADING = {
    "model": "Shared across everything",
    "state": "One per state",
    "measurement": "One per measurement",
}

#: What each scope asserts, phrased to complement the heading rather than
#: repeat it.
_SCOPE_PROSE = {
    "model": "`per: model`, nothing in the experiment could change it",
    "state": "`per: state`, the experiment changed it between states",
    "measurement": "`per: measurement`, a genuine per-file nuisance",
}

#: What each nuisance parameter is actually absorbing, and what it costs to be
#: wrong about it. These are the ones a reader most often needs explaining.
_NUISANCE_PROSE = {
    "intensity": (
        "the incident-beam normalisation. Where two angle segments disagree "
        "about the same sample, this is what absorbs it -- see "
        "`nrw data overlap`. Left tied when the segments already agree."
    ),
    "background": (
        "a flat additive background, which matters only at the highest Q "
        "where the signal approaches the noise floor."
    ),
    "theta_offset": (
        "a small error in the incident angle, from sample alignment. It shifts "
        "the whole curve in Q; leaving it fixed when the sample was misaligned "
        "pushes the error into a layer thickness."
    ),
    "sample_broadening": (
        "extra angular divergence beyond the calculated resolution, from "
        "sample curvature or mosaic. It damps the fringes, so leaving it fixed "
        "when it is real makes every interface look rougher than it is."
    ),
}


def explain(
    table: ParameterTable,
    *,
    spec_path: Path | None = None,
    spec_sha256: str = "",
    now: datetime | None = None,
) -> str:
    """Render the explanation.

    Args:
        table: The resolved parameter table.
        spec_path: Path to the spec, relative to the project root.
        spec_sha256: Digest of the spec, recorded for staleness detection.
        now: Timestamp. Injectable so golden tests are stable.

    Returns:
        The complete markdown document.
    """
    spec = table.spec
    stamp = (now or datetime.now(UTC)).strftime("%Y-%m-%dT%H:%M:%SZ")

    blocks = [
        _front_matter(spec, spec_path, spec_sha256, stamp),
        _what_is_modelled(table),
        _the_stack(table),
        _what_is_shared(table),
        _what_varies_with_time(table),
        _nuisance(table),
        _assumptions(table),
        _budget(table),
        _how_to_check(spec_path),
    ]
    return "\n\n".join(block for block in blocks if block).rstrip() + "\n"


def _front_matter(
    spec: Any, spec_path: Path | None, spec_sha256: str, stamp: str
) -> str:
    lines = [
        f"# {spec.name}",
        "",
        "<!-- GENERATED BY nr-workbench -- DO NOT EDIT.",
        "     Regenerate with `nrw model generate`. Edit the spec, not this.",
    ]
    if spec_path is not None:
        lines.append(f"     spec:        {spec_path.as_posix()}")
    if spec_sha256:
        lines.append(f"     spec sha256: {spec_sha256}  ({SPEC_HASH_MARKER})")
    lines.append(f"     generated:   {stamp} -->")
    if spec.description and spec.description.strip():
        lines += ["", spec.description.strip()]
    return "\n".join(lines)


def _what_is_modelled(table: ParameterTable) -> str:
    """The measurements, and where their angles came from."""
    lines = ["## What is being modelled", ""]

    total = table.n_experiments
    lines.append(
        f"{total} measurement{'s' if total != 1 else ''} of sample "
        f"`{table.spec.sample}`, fitted together so that everything physically "
        "shared is described by one number rather than several."
    )
    lines += [
        "",
        "| Group | Kind | Measurements | Angle(s) | Notes |",
        "|---|---|---|---|---|",
    ]

    series_names = {series.name for series in table.spec.series}
    for group, measurements in table.measurements.items():
        angles = sorted({m.theta for m in measurements})
        angle_text = ", ".join(f"{a:g}°" for a in angles)
        times = [m.time for m in measurements if m.time is not None]
        if group in series_names:
            kind = "time series"
            note = f"t = {min(times):g}–{max(times):g} s" if times else "no time axis"
        else:
            kind = "steady state"
            note = f"{len(measurements)} angle segment(s), co-refined"
        lines.append(
            f"| `{group}` | {kind} | {len(measurements)} | {angle_text} | {note} |"
        )

    lines += [
        "",
        "Angles are the values recorded in each file's own `# Meta:` header, not "
        "the nominal instrument settings. They set the resolution through "
        "`dT = dq/q · tan(θ)`.",
    ]
    return "\n".join(lines)


def _the_stack(table: ParameterTable) -> str:
    """The layer structure and its starting values."""
    spec = table.spec
    lines = [
        "## The layer stack",
        "",
        "Ambient first, substrate last. Thicknesses and roughnesses are "
        "starting values; whether each is fitted is in the next section.",
        "",
        "| Layer | Material | SLD (10⁻⁶ Å⁻²) | Thickness (Å) | Roughness (Å) |",
        "|---|---|---|---|---|",
    ]
    for index, layer in enumerate(spec.stack):
        material = spec.materials.get(layer.material)
        rho = f"{material.rho:g}" if material is not None else "?"
        last = index == len(spec.stack) - 1
        thickness = "semi-infinite" if last else f"{layer.thickness:g}"
        roughness = "—" if last else f"{layer.roughness:g}"
        lines.append(
            f"| `{layer.name}` | {layer.material} | {rho} | {thickness} | {roughness} |"
        )
    return "\n".join(lines)


def _what_is_shared(table: ParameterTable) -> str:
    """Free parameters, grouped by scope, in the language of the schema."""
    by_scope: dict[str, list[Any]] = defaultdict(list)
    for parameter in table.free:
        by_scope[_scope_of(parameter.key)].append(parameter)

    lines = [
        "## What is fitted, and what is held equal to what",
        "",
        "Co-refinement means saying which measurements share a number. Each "
        "parameter below is created once and read from everywhere it applies, "
        "so there is no possibility of two measurements drifting apart on a "
        "quantity the model says is one value.",
    ]

    for scope in ("model", "state", "measurement"):
        parameters = by_scope.get(scope)
        if not parameters:
            continue
        lines += [
            "",
            f"### {_SCOPE_HEADING[scope]} — {_SCOPE_PROSE[scope]}",
            "",
        ]
        if scope == "model":
            lines.append(
                "These cannot change between measurements. A substrate is a "
                "substrate; a material that was not chemically altered has one SLD."
            )
        elif scope == "state":
            lines.append(
                "One value per state, because the experiment changed something "
                "between them. Within a state, every angle segment shares it."
            )
        else:
            lines.append(
                "One value per individual measurement. This is deliberate and "
                "rare — it is for a genuine per-file nuisance, never for structure."
            )
        lines += ["", "| Parameter | Start | Range |", "|---|---|---|"]
        for parameter in sorted(parameters, key=lambda p: p.key):
            if parameter.fixed:
                bounds = "fixed"
            elif parameter.bounds:
                bounds = f"{parameter.bounds[0]:g} to {parameter.bounds[1]:g}"
            else:
                bounds = "unbounded"
            lines.append(f"| `{parameter.key}` | {parameter.value:g} | {bounds} |")

    fixed_layers = _fixed_layers(table)
    if fixed_layers:
        lines += [
            "",
            "### Held at their starting values",
            "",
            "Not fitted, so their uncertainty does not propagate into anything "
            "else — and any error in them is absorbed by whatever *is* free:",
            "",
            ", ".join(f"`{name}`" for name in fixed_layers) + ".",
        ]
    return "\n".join(lines)


def _what_varies_with_time(table: ParameterTable) -> str:
    """Constraints, with the arithmetic they actually apply."""
    spec = table.spec
    if not spec.constraints:
        return ""

    lines = [
        "## What changes during the time series, and how",
        "",
        "A constraint replaces one free parameter per slice with a *functional "
        "form*: the slice values are computed from a handful of numbers rather "
        "than fitted independently. The formulas below are the ones the "
        "generated script evaluates, not a paraphrase of them.",
    ]

    for constraint in spec.constraints:
        lines.extend(_constraint_section(table, constraint))

    return "\n".join(lines)


def _constraint_section(table: ParameterTable, constraint: Any) -> list[str]:
    """One constraint: the formula, the numbers in it, and what it costs."""
    measurements = table.measurements.get(constraint.series, [])
    times = [m.time for m in measurements if m.time is not None]
    n = len(measurements)
    start = getattr(constraint, "from_", None)
    end = getattr(constraint, "to", None)

    lines = ["", f"### `{constraint.series}` — {constraint.form}", ""]
    if times:
        lines.append(f"{n} slices, t = {min(times):g} to {max(times):g} s.")
    else:
        lines.append(f"{n} slices.")

    lines += ["", "```", *_formula(constraint, start, end), "```", ""]
    lines.append(_form_prose(constraint) + ".")

    extra = _extra_free(table, constraint)
    if extra:
        lines += [
            "",
            "This form fits its own shape parameters:",
            "",
        ]
        lines += [
            f"- `{parameter.key}` — start {parameter.value:g}"
            + (
                f", range {parameter.bounds[0]:g} to {parameter.bounds[1]:g}"
                if parameter.bounds
                else ""
            )
            for parameter in extra
        ]
    elif start and end:
        lines += [
            "",
            f"**No new free parameters.** The endpoints are `{start}`'s and "
            f"`{end}`'s own values, which the steady-state data already "
            "constrains, so the series is described entirely by the states "
            "either side of it.",
        ]

    schedule = _schedule(constraint, measurements)
    if schedule:
        lines += ["", *schedule]

    paths = list(constraint.paths)
    lines += ["", "Applied to:", ""]
    lines += [f"- `{path}`" for path in paths]

    determined = sum(
        1
        for expression in table.expressions
        if expression.key.split("@", 1)[-1].split("#", 1)[0] == constraint.series
    )
    if determined:
        lines += [
            "",
            f"That is **{determined} slice values** "
            f"({len(paths)} path{'s' if len(paths) != 1 else ''} x {n} slices) "
            f"computed from {len(extra) if extra else 'no'} new free "
            f"parameter{'' if len(extra) == 1 else 's'}.",
        ]
    return lines


def _formula(constraint: Any, start: str | None, end: str | None) -> list[str]:
    """The expression the generated script evaluates, for slice i."""
    a = f"p[{start}]" if start else "p_start"
    b = f"p[{end}]" if end else "p_end"
    forms = {
        "linear_in_index": [
            f"p_i  =  {a} + ({b} - {a}) * f_i",
            "",
            "f_i  =  i / (N - 1)            fraction by slice index",
        ],
        "linear_in_time": [
            f"p_i  =  {a} + ({b} - {a}) * f_i",
            "",
            "f_i  =  (t_i - t_0) / (t_last - t_0)    fraction by elapsed time",
        ],
        "piecewise_linear": [
            "p_i  =  k_left + (k_right - k_left) * w_i",
            "",
            "k_*  =  fitted knot values, evenly spaced in slice index",
            "w_i  =  position of slice i between its two bracketing knots",
        ],
        "exponential": [
            f"p_i  =  {b} + ({a} - {b}) * exp(-(t_i - t_0) / tau)",
            "",
            "tau  =  fitted decay constant, in seconds",
        ],
        "logistic": [
            f"p_i  =  {a} + ({b} - {a}) / (1 + exp(-(t_i - t_half) / w))",
            "",
            "t_half =  fitted midpoint, in seconds",
            "w      =  fitted width; large w is a slow transition",
        ],
        "free": ["p_i  =  fitted independently for every slice i"],
        "fixed": [f"p_i  =  {a}      the same value in every slice"],
    }
    return forms.get(constraint.form, [f"form: {constraint.form}"])


def _form_prose(constraint: Any) -> str:
    """Say what a constraint form asserts, in words.

    The formula says what is computed; this says why that shape was chosen.
    """
    start = getattr(constraint, "from_", None)
    end = getattr(constraint, "to", None)
    forms = {
        "linear_in_index": (
            f"Each listed quantity moves in equal steps from its `{start}` value "
            f"to its `{end}` value, one step per slice"
        ),
        "linear_in_time": (
            f"Each listed quantity moves linearly **in time** from its `{start}` "
            f"value to its `{end}` value. Time rather than slice index, because "
            "the intervals are not equally spaced"
        ),
        "piecewise_linear": (
            f"Each listed quantity follows a piecewise-linear path from `{start}` "
            f"to `{end}` through fitted knots -- for a trajectory with structure "
            "no closed form captures, without going to one parameter per slice"
        ),
        "exponential": (
            "Each listed quantity relaxes exponentially towards its final value. "
            "Use when the process is a first-order approach to equilibrium"
        ),
        "logistic": (
            "Each listed quantity follows a logistic curve: an induction period, "
            "a transition, then a plateau. This is the form to reach for when "
            "`nrw tnr assess` reports a sigmoidal a(t)"
        ),
        "free": (
            "Each listed quantity is fitted independently in every slice. No "
            "functional form is assumed, at the cost of one free parameter per "
            "slice per path"
        ),
        "fixed": "Each listed quantity is pinned and does not change",
    }
    return forms.get(constraint.form, f"Form `{constraint.form}` applied")


#: How many slices to tabulate before eliding the middle.
_SCHEDULE_ROWS = 3


def _schedule(constraint: Any, measurements: list[Any]) -> list[str]:
    """Tabulate the interpolation fractions, and show why time != index.

    Only for the two linear forms, where the fraction is the whole content of
    the model and the index/time difference is the reason to prefer one.
    """
    if constraint.form not in ("linear_in_index", "linear_in_time"):
        return []
    times = [m.time for m in measurements if m.time is not None]
    n = len(measurements)
    if n < 2 or len(times) != n:
        return []

    span = times[-1] - times[0]
    if span <= 0:
        return []

    def by_time(i: int) -> float:
        return (times[i] - times[0]) / span

    def by_index(i: int) -> float:
        return i / (n - 1)

    shown = sorted({0, n // 2, n - 1}) if n <= 2 * _SCHEDULE_ROWS else None
    rows = shown if shown is not None else [0, 1, n // 2, n - 2, n - 1]

    lines = [
        "| Slice | t (s) | f by time | f by index |",
        "|---|---|---|---|",
    ]
    previous = -1
    for i in rows:
        if i - previous > 1:
            lines.append("| … | | | |")
        lines.append(f"| {i} | {times[i]:g} | {by_time(i):.3f} | {by_index(i):.3f} |")
        previous = i

    worst = max(range(n), key=lambda i: abs(by_time(i) - by_index(i)))
    gap = abs(by_time(worst) - by_index(worst))
    if gap > 0.01:
        chosen, other = (
            ("time", "index")
            if constraint.form == "linear_in_time"
            else ("index", "time")
        )
        lines += [
            "",
            f"The two disagree most at slice {worst}: "
            f"{by_time(worst):.3f} by time against {by_index(worst):.3f} by "
            f"index, a gap of {gap:.3f}. This model interpolates by "
            f"**{chosen}**; choosing {other} would place that slice "
            f"{gap * 100:.1f}% of the way along the trajectory from where this "
            "one puts it.",
        ]
    else:
        lines += [
            "",
            "The slices are near enough evenly spaced that index and time give "
            "the same answer here.",
        ]
    return lines


def _extra_free(table: ParameterTable, constraint: Any) -> list[Any]:
    """Free parameters this constraint introduced -- tau, t_half, knots."""
    marker = f"@{constraint.series}"
    structural = {"thickness", "roughness", "rho", "irho"}
    found = []
    for parameter in table.free:
        if marker not in parameter.key:
            continue
        attribute = parameter.key.split("@", 1)[0].split(".")[-1]
        if attribute in structural or parameter.key.startswith("probe."):
            continue
        found.append(parameter)
    return found


def _nuisance(table: ParameterTable) -> str:
    """Probe parameters and what each is absorbing."""
    present = {
        _attribute_of(parameter.key)
        for parameter in table.free
        if parameter.key.startswith("probe.")
    }
    if not present:
        return ""

    lines = [
        "## Instrument parameters, and what they absorb",
        "",
        "These describe the measurement rather than the sample. Each is here "
        "because leaving it out would force its error into a layer.",
        "",
    ]
    for attribute in sorted(present):
        prose = _NUISANCE_PROSE.get(attribute, "an instrument parameter.")
        lines.append(f"- **`probe.{attribute}`** — {prose}")

    absent = sorted(set(_NUISANCE_PROSE) - present)
    if absent:
        lines += [
            "",
            "Not fitted: "
            + ", ".join(f"`probe.{name}`" for name in absent)
            + ". Each is therefore assumed negligible.",
        ]
    return "\n".join(lines)


def _assumptions(table: ParameterTable) -> str:
    """Everything taken as given rather than measured or fitted."""
    spec = table.spec
    lines = [
        "## Assumptions",
        "",
        "Things this model takes as true without fitting them. Each is a place "
        "the result could be wrong without the fit complaining.",
        "",
    ]

    lines.append(
        "1. **Angular-only resolution.** `dT = dq/q · tan(θ)` with `dL = 0` — "
        "the BL-4B convention. Fits made under a different resolution "
        "convention are not numerically comparable with this one."
    )
    lines.append(
        f"2. **The `dQ` column is {'FWHM' if spec.probe.dq_is_fwhm else 'sigma'}.** "
        "Getting this wrong scales every resolution by 2.355, which the fit "
        "compensates for with roughness."
    )
    lines.append(
        "3. **Each layer is uniform with an error-function interface.** A "
        "concentration gradient — common for a swollen polymer — is not that, "
        "and a slab model describes it by inflating the roughness."
    )

    index = 4
    materials = ", ".join(
        f"`{name}` = {material.rho:g}"
        for name, material in spec.materials.items()
        if not _is_fitted(table, f"{name}.rho")
    )
    if materials:
        lines.append(
            f"{index}. **These SLDs are taken from literature, not fitted:** "
            f"{materials}."
        )
        index += 1

    fixed_layers = _fixed_layers(table)
    if fixed_layers:
        lines.append(
            f"{index}. **These layers are held at their starting values:** "
            + ", ".join(f"`{name}`" for name in fixed_layers)
            + "."
        )
        index += 1

    thin = _thin_layers(spec)
    if thin:
        lines.append(
            f"{index}. **Layers below the resolution limit.** "
            + ", ".join(f"`{name}` ({thickness:g} Å)" for name, thickness in thin)
            + ". Reflectivity constrains a thin layer mainly through the product "
            "of contrast and thickness, so its SLD and thickness are individually "
            "poorly determined even when their product is not. See the "
            "`thin-layer-degeneracy` skill."
        )
        index += 1

    if table.warnings:
        lines += ["", "Resolution also reported:", ""]
        lines += [f"- {warning}" for warning in table.warnings]
    return "\n".join(lines)


def _budget(table: ParameterTable) -> str:
    """The degrees-of-freedom summary."""
    return "\n".join(
        [
            "## Degrees of freedom",
            "",
            f"- **{table.n_experiments}** experiments",
            f"- **{table.n_free}** free parameters",
            f"- **{len(table.expressions)}** values determined by constraints "
            "rather than fitted",
            "",
            "The ratio is the point of co-refining: the constrained values are "
            "described by the free ones, so the data constrains a small number "
            "of physical quantities rather than a large number of independent "
            "ones.",
        ]
    )


def _how_to_check(spec_path: Path | None) -> str:
    """The commands that verify what this document claims."""
    spec = spec_path.as_posix() if spec_path else "<spec.yaml>"
    return "\n".join(
        [
            "## How to check this",
            "",
            "```bash",
            f"nrw model validate {spec}      # schema and semantic checks",
            f"nrw model preview  {spec} --build   # builds it, reports initial χ²",
            "nrw data overlap <sample>            # do the angle segments agree",
            "```",
            "",
            "The generated script ends with `_check_links()`, which asserts at "
            "runtime that everything this document says is shared really is one "
            "object. A broken tie fails loudly rather than producing a plausible "
            "wrong answer.",
        ]
    )


# --------------------------------------------------------------------------
# Small helpers
# --------------------------------------------------------------------------


def _scope_of(key: str) -> str:
    """Read the scope out of a table key like ``Cu.thickness@ocv1``."""
    if "@" not in key:
        return "model"
    suffix = key.split("@", 1)[1]
    if suffix == "model":
        return "model"
    return "measurement" if "#" in suffix else "state"


def _attribute_of(key: str) -> str:
    """``probe.intensity@ocv1`` -> ``intensity``."""
    head = key.split("@", 1)[0]
    return head.split(".", 1)[1] if "." in head else head


def _is_fitted(table: ParameterTable, path: str) -> bool:
    """Whether any free parameter addresses this path."""
    return any(
        parameter.key.split("@", 1)[0] == path and not parameter.fixed
        for parameter in table.free
    )


def _fixed_layers(table: ParameterTable) -> list[str]:
    """Layers with no fitted parameter at all."""
    spec = table.spec
    fitted = {
        parameter.key.split("@", 1)[0].split(".", 1)[0] for parameter in table.free
    }
    constrained = {
        expression.key.split("@", 1)[0].split(".", 1)[0]
        for expression in table.expressions
    }
    touched = fitted | constrained
    return [layer.name for layer in spec.stack if layer.name not in touched]


#: Real-space resolution limit for a typical REF_L Q_max of 0.2 1/A.
_RESOLUTION_LIMIT = 30.0


def _thin_layers(spec: Any) -> list[tuple[str, float]]:
    """Layers thinner than the resolution limit, excluding the substrate."""
    found = []
    for layer in spec.stack[:-1]:
        thickness = float(layer.thickness or 0.0)
        if 0 < thickness < _RESOLUTION_LIMIT:
            found.append((layer.name, thickness))
    return found
